### ISSUE TITLE
Debugger.clean() is not using the clean_formatter attribute

### ISSUE THREAD

**Issue by evandrocoan** [evandrocoan/debugtools#1]
```
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: File "F:\Python\lib\logging\handlers.py", line 73, in emit
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: logging.FileHandler.emit(self, record)
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: File "F:\Python\lib\logging\__init__.py", line 1070, in emit
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: StreamHandler.emit(self, record)
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: File "F:\Python\lib\logging\__init__.py", line 998, in emit
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: self.handleError(record)
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: Message: 'PythonLanguageServer, self.config: %s'
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: Arguments: (<pyls.config.config.Config object at 0x000001C732E20D30>,)
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: --- Logging error ---
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: Traceback (most recent call last):
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: File "F:\Python\lib\logging\__init__.py", line 994, in emit
16:37:47:451.338291 8.01e-03 - pyls.config.source.read_config_from_files:52 DEBUG - Using cached configuration for ()
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: stream.write(msg)
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: AttributeError: 'NoneType' object has no attribute 'write'
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: Call stack:
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: File "F:\Python\lib\threading.py", line 884, in _bootstrap
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: self._bootstrap_inner()
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: File "F:\Python\lib\threading.py", line 916, in _bootstrap_inner
22:00:00:000.000000 0.00e+00 - LSP.plugin.core.rpc.No Function:0 - LSP server: self.run()
```

**Comment by evandrocoan** [comment]
It was only partially fixed. The problem happens here:
```python

            if file_handler:
                file_handler_formatter = file_handler.formatter
                file_handler.formatter = self.clean_formatter

            kwargs['debug_level'] = debug_level
            self._log_clean( msg % args )
```
The current log handler has no `file_formatter` attribute, only the active log handler has such thing. This is why it was not working. Because when `log.clean` is called on a non-active log handler which forwards it to the active parent logger.

**Comment by evandrocoan** [comment]
I am not sure if this was fixed on commit https://github.com/evandrocoan/debugtools/commit/93a8519d6a1c79029e0e325978ba30d04d988a73, but the current master branch has a unit test for this and it is passing:
https://github.com/evandrocoan/debugtools/blob/545c0b798faf6913fc104d9afdab5f5238eabd00/tests/testing/main_unit_tests.py#L451-L464
